const OCLC_SEARCH_ENDPOINT = "/branch/{branchId}/perspective/{perspectiveId}/search";

const rows = [
  {
    order: 1,
    field: "Vrij zoeken",
    inputType: "vrij veld",
    status: "JA",
    oclcParameter: "term + searchScope",
    valuePattern: "term=<tekst>&searchScope=anything",
    source: "invoer",
    example: "term=kikker&searchScope=anything",
    note: "Rechtstreeks OCLC Discovery-zoekterm; de testhost en concrete test-perspective worden niet in dit overzicht opgenomen.",
  },
  {
    order: 2,
    field: "Titel",
    inputType: "vrij veld",
    status: "JA",
    oclcParameter: "term + searchScope",
    valuePattern: "term=<titel>&searchScope=title",
    source: "invoer",
    example: "term=kikker&searchScope=title",
    note: "Als Vrij zoeken al gevuld is, wordt Titel aanvullend als termFilter=title:<titel> meegestuurd zodat beide criteria behouden blijven.",
  },
  {
    order: 3,
    field: "Auteur",
    inputType: "vrij veld",
    status: "JA",
    oclcParameter: "facetFilter",
    valuePattern: "authorFacet:<auteur>",
    source: "invoer",
    example: "facetFilter=authorFacet:Linden, Martijn van der",
    note: "OCLC documenteert authorFacet expliciet als facetFilter. URL-encoding van komma en spaties gebeurt bij het opbouwen van de request.",
  },
  {
    order: 4,
    field: "Formaat",
    inputType: "lijst",
    status: "JA",
    oclcParameter: "facetFilter",
    valuePattern: "mediumTypeCode:<code>",
    source: "mediumtypecode.txt",
    example: "facetFilter=mediumTypeCode:BOE",
    note: "Code uit de bestaande WISE-metadatalijst wordt rechtstreeks gebruikt.",
  },
  {
    order: 5,
    field: "Bibliotheek",
    inputType: "lijst",
    status: "JA",
    oclcParameter: "facetFilter",
    valuePattern: "branchId:<id>",
    source: "branch.txt",
    example: "facetFilter=branchId:1001",
    note: "Dropdown-label komt uit name; de OCLC-waarde komt rechtstreeks uit id.",
  },
  {
    order: 6,
    field: "Plaatsingscode",
    inputType: "vrij veld",
    status: "CHECK",
    oclcParameter: "termFilter",
    valuePattern: "placementCode:<waarde>",
    source: "invoer",
    example: "termFilter=placementCode:<waarde>",
    note: "Beschikbaar voor testdoeleinden, maar de exacte geïndexeerde OCLC-veldnaam moet nog worden bevestigd.",
  },
  {
    order: 7,
    field: "Jaar",
    inputType: "jaar (4 cijfers)",
    status: "JA",
    oclcParameter: "facetFilter",
    valuePattern: "customPublicationYear:<jaar>",
    source: "invoer",
    example: "facetFilter=customPublicationYear:2025",
    note: "OCLC ondersteunt customPublicationYear rechtstreeks met een los jaartal; geen Zulu-datum nodig.",
  },
  {
    order: 8,
    field: "Jaar tot",
    inputType: "jaar (4 cijfers)",
    status: "JA",
    oclcParameter: "facetFilter",
    valuePattern: "customPublicationYear:<van>-<tot>",
    source: "invoer",
    example: "facetFilter=customPublicationYear:2022-2023",
    note: "Inclusief jaarinterval. Bij één ingevuld jaar wordt alleen dat jaar gebruikt.",
  },
  {
    order: 9,
    field: "Genre",
    inputType: "lijst",
    status: "JA",
    oclcParameter: "facetFilter",
    valuePattern: "genreCode:<code>",
    source: "genrecode.txt",
    example: "facetFilter=genreCode:DE",
    note: "Code uit de bestaande WISE-metadatalijst wordt rechtstreeks gebruikt.",
  },
  {
    order: 10,
    field: "Taal",
    inputType: "lijst",
    status: "JA",
    oclcParameter: "facetFilter",
    valuePattern: "languageCode:<code>",
    source: "languagecode.txt",
    example: "facetFilter=languageCode:GER",
    note: "Code uit de bestaande WISE-metadatalijst wordt rechtstreeks gebruikt.",
  },
  {
    order: 11,
    field: "Onderwerp",
    inputType: "vrij veld",
    status: "CHECK",
    oclcParameter: "facetFilter",
    valuePattern: "subject:<waarde>",
    source: "invoer",
    example: "facetFilter=subject:<waarde>",
    note: "De mockup kan dit rechtstreeks testen; exacte matching/waardeconventie moet nog worden bevestigd.",
  },
  {
    order: 12,
    field: "ISSN",
    inputType: "vrij veld",
    status: "CHECK",
    oclcParameter: "termFilter",
    valuePattern: "issn:<waarde>",
    source: "invoer",
    example: "termFilter=issn:<waarde>",
    note: "Beschikbaar voor testdoeleinden; veldnaam/normalisatie nog bevestigen.",
  },
  {
    order: 13,
    field: "Uitgever",
    inputType: "vrij veld",
    status: "CHECK",
    oclcParameter: "termFilter",
    valuePattern: "publisher:<waarde>",
    source: "invoer",
    example: "termFilter=publisher:<waarde>",
    note: "Beschikbaar voor testdoeleinden; geïndexeerde OCLC-veldnaam nog bevestigen.",
  },
  {
    order: 14,
    field: "ISBN",
    inputType: "vrij veld",
    status: "CHECK",
    oclcParameter: "termFilter",
    valuePattern: "isbn:<waarde>",
    source: "invoer",
    example: "termFilter=isbn:<waarde>",
    note: "Spaties en koppeltekens worden verwijderd; exacte OCLC-termFilterwerking nog bevestigen.",
  },
  {
    order: 15,
    field: "Reeks",
    inputType: "vrij veld",
    status: "JA",
    oclcParameter: "facetFilter",
    valuePattern: "series:<waarde>",
    source: "invoer",
    example: "facetFilter=series:Tijgerlezen",
    note: "Rechtstreeks OCLC-facet; hierdoor kan Reeks met andere criteria worden gecombineerd zonder eigen qs/scope-vertaallaag.",
  },
  {
    order: 16,
    field: "Collectie",
    inputType: "lijst",
    status: "CHECK",
    oclcParameter: "",
    valuePattern: "",
    source: "nog te bepalen",
    example: "",
    note: "Nog geen bevestigde OCLC-mapping of vullijst.",
  },
  {
    order: 17,
    field: "Jeugd",
    inputType: "lijst",
    status: "JA",
    oclcParameter: "facetFilter",
    valuePattern: "targetAudienceCode:<code>",
    source: "targetaudiencecode.txt",
    example: "facetFilter=targetAudienceCode:AB",
    note: "Code uit de bestaande WISE-metadatalijst wordt rechtstreeks gebruikt.",
  },
  {
    order: 18,
    field: "Inhoud",
    inputType: "vrij veld",
    status: "CHECK",
    oclcParameter: "termFilter",
    valuePattern: "content:<waarde>",
    source: "invoer",
    example: "termFilter=content:<waarde>",
    note: "Beschikbaar voor testdoeleinden; geïndexeerde OCLC-veldnaam nog bevestigen.",
  },
  {
    order: 19,
    field: "Aanwezig",
    inputType: "checkbox",
    status: "JA",
    oclcParameter: "filterAvailableTitles",
    valuePattern: "true",
    source: "invoer",
    example: "filterAvailableTitles=true",
    note: "Rechtstreekse OCLC Discovery-queryparameter.",
  },
];

function escapeCsv(value) {
  const stringValue = value === null || value === undefined ? "" : String(value);
  if (/[";\n\r]/.test(stringValue)) return `"${stringValue.replace(/"/g, '""')}"`;
  return stringValue;
}

export const ADVANCED_SEARCH_MAPPING_ROWS = rows.map((row) => ({
  ...row,
  oclcEndpoint: OCLC_SEARCH_ENDPOINT,
}));

export function toAdvancedSearchMappingCsv(mappingRows = ADVANCED_SEARCH_MAPPING_ROWS) {
  const columns = [
    ["order", "Volgorde"],
    ["field", "Veld"],
    ["inputType", "Invoer"],
    ["status", "Status"],
    ["oclcParameter", "OCLC parameter"],
    ["oclcEndpoint", "OCLC endpoint"],
    ["valuePattern", "Waarde / patroon"],
    ["source", "Bron keuzelijst"],
    ["example", "Voorbeeld"],
    ["note", "Opmerking"],
  ];

  return [
    columns.map(([, label]) => escapeCsv(label)).join(";"),
    ...mappingRows.map((row) => columns.map(([key]) => escapeCsv(row?.[key])).join(";")),
  ].join("\n");
}
