const exactLabels = {
  id: "Titelnummer",
  title: "Titel",
  mainTitle: "Hoofdtitel",
  subtitle: "Ondertitel",
  volume: "Deelnummer",
  volumeTitle: "Deeltitel",
  "author.description": "Auteur",
  "author.addition": "Auteurfunctie",
  "author.qualifier": "Levensjaren / kwalificatie auteur",
  "author.thesaurusNumber": "Thesaurusnummer auteur",
  contents: "Inhoud",
  contentsSchoolWise: "Samenvatting SchoolWise",
  "media.code": "Materiaalcode",
  "media.icon": "Materiaalicoon",
  "media.description": "Mediumsoort",
  "isbn[]": "ISBN",
  "ppn[]": "PPN-nummer",
  "imageUrls.small": "Cover-URL klein",
  "imageUrls.medium": "Cover-URL middel",
  "imageUrls.large": "Cover-URL groot",
  origin: "Bron/provider",
  "language[].code": "Taalcode publicatie",
  "language[].description": "Taal",
  publicationYear: "Publicatiejaar",
  available: "Beschikbaarheidsstatus hoofdoverzicht",
  allowHolds: "Reserveren toegestaan",
  annotationCollation: "Collatie",
  annotationEdition: "Editie",
  annotationNoMarc: "Noot",
  imprint: "Uitgave",
  imprintExtended: "Uitgebreid impressum",
  acquisitionInformation: "Aanschafinfo",
  "subjects[].description": "Onderwerpen",
  "genre[].description": "Genre",
  "genre[].code": "Genrecode",
  "classification[].description": "Classificatie",
  "classification[].classificationSystem": "Classificatiesysteem",
  "collaborators[].description": "Medewerker",
  "collaborators[].addition": "Functie medewerker",
  "titleSeries[].description": "Serie",
  "titleSeries[].addition": "Nummer binnen reeks",
  "audience.description": "Leeftijdscategorie",
  "youthMaterial.description": "Materiaal",
  "audience.code": "Doelgroepcode",
  adult: "Doelgroep volwassenen",
  youth: "Doelgroep jeugd",
  source: "Catalogusbron",
  "[].title": "Titel",
  "[].author": "Auteur",
  "[].description": "Samenvatting / beschrijving",
  "[].publicationYear": "Jaar van uitgave",
  "[].isbn": "ISBN-nummer",
  "[].ppn": "PPN-nummer",
  "[].medium.code": "Materiaalcode",
  "[].volumeNumber": "Deelnummer",
  "[].volumeName": "Deeltitel",
  "[].momkeys": "MOM-sleutels (o.a. cover/NBD)",
  "[].categoryYouth": "Doelgroep jeugd",
  "[].categoryAdult": "Doelgroep volwassenen",
  "[].categoryNarrative": "Verhalend",
  "[].categoryInformative": "Informatief",
  "[].availability[].status": "Beschikbaarheidsstatus per catalogusgroep",
  "[].availability[].statusCode": "Statuscode per catalogusgroep",
  "[].availability[].catGroup": "Catalogusgroep",
  "[].holdAllowed": "Reserveren toegestaan",
  "[].numberOfItems": "Aantal exemplaren",
  "[].bibliographicRecordId": "Bibliografisch record-ID",
  "[].branchName": "Locatie",
  "[].branchId": "Vestigings-ID",
  "[].callNumber": "Plaats",
  "[].effectiveStatus": "Beschikbaarheid",
  "[].effectiveStatusCode": "Exemplaarstatuscode",
  "[].returnDate": "Inleverdatum (onderdeel beschikbaarheid)",
  "[].barcode": "Exemplaarbarcode",
  "[].location": "Locatie",
  "[].subLocation": "Deellocatie",
  "[].shelfCode": "Kastcode",
  "[].shelfDescription": "Waar te vinden",
  "[].temporaryShelfCode": "Tijdelijke kastcode",
  "[].volume": "Exemplaar-deel",
  "[].volumeId": "Exemplaar-deel-ID",
  "items[].id": "WISE titel-ID aanbevolen titel",
  "items[].title": "Aanbevolen titel",
  "items[].author": "Auteur aanbevolen titel",
  "items[].publicationYear": "Jaar aanbevolen titel",
  "items[].medium.code": "Materiaalcode aanbevolen titel",
};

const termLabels = {
  searchable: "Doorzoekbaar",
  type: "Type",
  qualifier: "Kwalificatie",
  addition: "Functie / toevoeging",
  thesaurusNumber: "Thesaurusnummer",
  code: "Code",
  description: "Omschrijving",
  icon: "Icoon",
  imageCode: "Afbeeldingscode",
  classificationSystem: "Classificatiesysteem",
  informative: "Informatief",
  narrative: "Verhalend",
  documentary: "Documentair",
  frontCatalog: "Voorkantcatalogus",
  backCatalog: "Achterkantcatalogus",
  titleType: "Titeltype",
  titleCategory: "Titelcategorie",
  targetGroup: "Doelgroep",
  price: "Prijs in centen",
  material: "Materiaal",
  id: "ID",
  pid: "PID",
  cWiseId: "CWise-ID",
  frbrkey: "FRBR-sleutel",
  frbrDocumentType: "FRBR-documenttype",
  public: "Publiek zichtbaar",
  publicBlock: "Publieke blokkade",
  futureOrdersBlock: "Toekomstige bestellingen geblokkeerd",
  blockHoldingSync: "Holding-synchronisatie geblokkeerd",
  ocnSyncBlock: "OCN-synchronisatie geblokkeerd",
  internalNote: "Interne notitie",
  message: "Bericht",
  scat: "SCAT-code",
  scatYouth: "SCAT-code jeugd",
  callNumber: "Plaatsingscode",
  headWord: "Hoofdwoord",
  itemCreationDate: "Aanmaakdatum exemplaar",
  orderNote: "Bestelnotitie",
  validationErrors: "Validatiefouten",
  href: "Link-URL",
  rel: "Linkrelatie",
  from: "Vanaf",
  to: "Tot en met",
};

const obaIstFields = new Set([
  "discovery|title", "discovery|mainTitle", "discovery|subtitle", "discovery|volume", "discovery|volumeTitle",
  "discovery|author.description", "discovery|author.addition", "discovery|contents", "discovery|media.code",
  "discovery|media.description", "discovery|isbn[]", "discovery|ppn[]", "discovery|language[].code",
  "discovery|language[].description", "discovery|publicationYear", "discovery|annotationCollation",
  "discovery|annotationEdition", "discovery|annotationNoMarc", "discovery|imprint", "discovery|subjects[].description",
  "discovery|imageUrls.small", "discovery|imageUrls.medium", "discovery|imageUrls.large", "discovery|available",
  "discovery|audience.code", "discovery|genre[].description", "discovery|genre[].code",
  "discovery|classification[].description", "discovery|collaborators[].description",
  "discovery|collaborators[].addition", "discovery|titleSeries[].description",
  "discovery|titleSeries[].addition", "discovery|audience.description", "discovery|adult", "discovery|youth",
  "title|[].title", "title|[].author", "title|[].description", "title|[].publicationYear", "title|[].isbn",
  "title|[].ppn", "title|[].medium.code", "title|[].volumeNumber", "title|[].volumeName", "title|[].genre",
  "title|[].categoryYouth", "title|[].categoryAdult", "title|[].momkeys",
  "availability|[].ppn", "availability|[].holdAllowed", "availability|[].availability[].status",
  "availability|[].availability[].statusCode", "items|[].branchName", "items|[].callNumber",
  "items|[].effectiveStatus", "items|[].effectiveStatusCode", "items|[].returnDate", "items|[].location",
  "items|[].subLocation", "items|[].shelfDescription", "items|[].volume",
]);

const noteOverrides = {
  "discovery|mainTitle": "Onderdeel van de samengestelde titel, samen met subtitle, volume en volumeTitle.",
  "discovery|subtitle": "Onderdeel van de samengestelde titel wanneer deze ruwe waarde gevuld is.",
  "discovery|volume": "Onderdeel van de samengestelde titel wanneer deze ruwe waarde gevuld is.",
  "discovery|volumeTitle": "Onderdeel van de samengestelde titel wanneer deze ruwe waarde gevuld is.",
  "discovery|author.description": "Ruwe OCLC-auteurswaarde; de naamvolgorde wordt niet aangepast. De zichtbare auteur linkt via facetFilter=authorFacet:<description> naar OCLC zoeken.",
  "discovery|author.addition": "Ruwe OCLC-functiecode; wordt niet vertaald.",
  "discovery|media.code": "Ruwe materiaalcode; wordt niet vertaald.",
  "discovery|imageUrls.small": "Ruwe cover-URL voor klein formaat.",
  "discovery|imageUrls.medium": "Ruwe cover-URL voor middelgroot formaat.",
  "discovery|imageUrls.large": "Ruwe cover-URL voor groot formaat.",
  "discovery|available": "Ruwe globale beschikbaarheidswaarde op titelniveau.",
  "discovery|annotationCollation": "Wordt als één ruwe waarde weergegeven en niet opgesplitst.",
  "discovery|imprint": "Wordt als één ruwe waarde weergegeven en niet opgesplitst.",
  "discovery|titleSeries[].description": "De zichtbare seriewaarde linkt via facetFilter=series:<description> naar OCLC zoeken.",
  "discovery|genre[].description": "De zichtbare genrewaarde linkt met genre.code via facetFilter=genreCode:<code> naar OCLC zoeken.",
  "discovery|subjects[].description": "De zichtbare onderwerpwaarde linkt via facetFilter=subject:<description> naar OCLC zoeken.",
  "discovery|audience.description": "Ruwe doelgroepomschrijving; wordt niet vertaald.",
  "discovery|audience.code": "Ruwe doelgroepcode; wordt niet vertaald.",
  "title|[].categoryYouth": "Ruwe doelgroepindicator uit /title. Bij uitsluitend true wordt Jeugd getoond en gekoppeld aan de zoekfilter audienceCode:JN.",
  "title|[].categoryAdult": "Ruwe doelgroepindicator uit /title. Bij uitsluitend true wordt Volwassenen getoond en gekoppeld aan de zoekfilter audienceCode:NJ.",
  "title|[].medium.code": "Ruwe materiaalcode uit /title; wordt niet vertaald.",
  "availability|[].availability[].status": "Ruwe beschikbaarheidsstatus op titel-/catalogusgroepniveau.",
  "availability|[].availability[].statusCode": "Ruwe statuscode; wordt niet vertaald.",
  "availability|[].numberOfItems": "Ruw aantal exemplaren; dit is geen statusvertaling.",
  "availability|[].holdAllowed": "Ruwe boolean voor de reserveermogelijkheid.",
  "items|[].callNumber": "Wordt op de detailpagina getoond als Plaats.",
  "items|[].effectiveStatus": "Wordt voor de detailpagina vertaald: AVAILABLE = Beschikbaar, MISSING = Niet beschikbaar, ON_HOLD/ON HOLD = Gereserveerd en ON_LOAN = Uitgeleend tot [inleverdatum].",
  "items|[].effectiveStatusCode": "Ruwe exemplaarstatuscode; wordt niet vertaald.",
  "items|[].returnDate": "Wordt bij ON_LOAN zonder tijd gecombineerd met de status: Uitgeleend tot [inleverdatum].",
  "recommendations|items[].title": "Ruwe titel uit de recommendation-response.",
  "recommendations|items[].author": "Ruwe auteurswaarde uit de recommendation-response.",
};

export function normalizeOclcDetailPath(path = "") {
  return String(path).replace(/\[\d+\]/g, "[]");
}

function humanizeSegment(segment) {
  const clean = segment.replace(/\[\]/g, "");
  if (termLabels[clean]) return termLabels[clean];
  return clean
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .replace(/^./, (character) => character.toUpperCase());
}

export function getOclcDetailFieldMeta(endpointKey, indexedPath) {
  const normalizedPath = normalizeOclcDetailPath(indexedPath) || "(response)";
  const siteName = exactLabels[normalizedPath]
    || normalizedPath.split(".").map(humanizeSegment).filter(Boolean).join(" – ")
    || "Response";
  const obaIst = obaIstFields.has(`${endpointKey}|${normalizedPath}`) ? "WEL" : "NIET";
  const opmerkingen = noteOverrides[`${endpointKey}|${normalizedPath}`]
    || (obaIst === "WEL"
      ? "Conceptuele tegenhanger op OBA IST; de ruwe OCLC-waarde wordt ongewijzigd weergegeven."
      : "Technisch OCLC-veld; geen zichtbare of functionele OBA IST-tegenhanger vastgesteld.");

  return { normalizedPath, siteName, obaIst, opmerkingen };
}
